### ISSUE TITLE
Error when building the pairs

### ISSUE THREAD

**Issue by julimox** [MobleyLab/alchemical-setup#1]
Hello,

I am trying to use alchemical setup with the files attached below.
The change is small, I am converting a methyl group to a hydrogen + 3 dummy atoms but somehow I get the following mistake in the pair building process:

Traceback (most recent call last):
  File "./alchemical-setup.py", line 544, in <module>
    buildPairs()                                                 # Part III.
  File "./alchemical-setup.py", line 323, in buildPairs
    molX.newtop_pairs = sorted(preprocessPairs(molA) + preprocessPairs(molB))
  File "./alchemical-setup.py", line 314, in preprocessPairs
    i_new = map_old_new[i]
KeyError: '17'

Do you have an idea what I might be doing wrong?

Thank you very much and best regards.

https://drive.google.com/folderview?id=0B2M9aqeJrxnYbUNGdzA3S1gxM1E&usp=sharing

**Comment by julimox** [comment]
A kind reminder in case this issue is getting forgotten.

**Comment by davidlmobley** [comment]
I'm looking at this.

**Comment by davidlmobley** [comment]
@julianzachmann - your map is at least partially incorrect, as you have atom 20 in A mapped to both atom 17 and atom 27. The error message could be more informative, however.

I think there also may be other problems with your map, in that it only has 27 entries but there are 28 atoms in your MCSS. So probably you're missing a mapping for some atom. 

I'll keep going and see if I can figure out exactly where you've gone wrong. And obviously this means we need to add some more error handling.

**Comment by julimox** [comment]
You are completely right! I'm sorry - my mistake!
I changed the map file and now it is working properly.

Thanks a lot!

**Comment by davidlmobley** [comment]
Right, I think your last two lines should have been:

```
30 27
31 28
```

Also, for future bug reports please include your .gro files as well, as I can't actually reproduce your problem without them. 

(For testing purposes, could you go ahead and provide them now, @julianzachmann ? I'd like to make the error messages more informative.)

**Comment by julimox** [comment]
I have now uploaded them to https://drive.google.com/open?id=0B2M9aqeJrxnYbUNGdzA3S1gxM1E

**Comment by davidlmobley** [comment]
Thanks. Working on adding better exception handling here.
