### ISSUE TITLE
NameError: global name 'parametersB' is not defined

### ISSUE THREAD

**Issue by camizanette** [MobleyLab/alchemical-setup#4]
I was using a different format of topologies files and I got this error saying the variable parametersB is not defined previously. The issue comes from Part IV, when it is processing the dihedrals and the top file format doesn't match with what the code is expecting, going to an exception in line 380. What I have noticed is acpype and parmed return different dihedrals functions types (9 and 1), and amb2gmx.pl returns the function type 3 (the one that works). Samples here: https://drive.google.com/folderview?id=0B5Hiv4aw8v8CWWU3N2ZVb2FsbWs&usp=sharing
There are two folders, one with topologies from Parmed and other from amb2gmx.pl.
Let me know if it does not work.

Traceback (most recent call last):
File "../../local/alchemical-setup-master/alchemical-setup.py", line 549, in 
buildBonded() # Part IV.
File "../../local/alchemical-setup-master/alchemical-setup.py", line 429, in buildBonded
postprocessDihedrals()
File "../../local/alchemical-setup-master/alchemical-setup.py", line 385, in postprocessDihedrals
if l['parameters'][-1] != parametersB[-1]:
NameError: global name 'parametersB' is not defined

**Comment by FEPanalysis** [comment]
December is the month when I will have a chance to look at it.

**Comment by davidlmobley** [comment]
Fixed by #6 .
